### ISSUE TITLE
C++ SDK Link Dead

### ISSUE THREAD

**Issue by mrmm2703** [misuta-robotto/misuta-robotto#21]
The current link to the C++ SDK (https://developer.softbankrobotics.com/Software/C%2B%2B/2.5.5/Windows/naoqi-sdk-2.5.5.5-win32-vs2013.zip) within the Makefile is dead.

The new link is https://community-static.aldebaran.com/resources/2.5.5/naoqi-sdk/naoqi-sdk-2.5.5.5-win32-vs2013.zip.

**Comment by patriksletmo** [comment]
Thanks for reporting this!
I will update the configuration so that it uses the new URL after I've had the time to verify it.
